package com.nexus.core.entities;

public enum ShipmentDocumentType {
	BILL_OF_LADING,
	PROOF_OF_DELIVERY,
	COMMERCIAL_INVOICE,
	PACKING_LIST,
	CERTIFICATE_OF_ORIGIN,
	CERTIFICATE_OF_ANALYSIS,
	INSURANCE_CERTIFICATE,
	CUSTOMS_DECLARATION,
	DANGEROUS_GOODS_DECLARATION,
	SHIPPING_INSTRUCTIONS,
	BOOKING_CONFIRMATION,
	OTHER
}