package com.nexus.core.entities;

public enum TrackingEventType {
	CREATED,
	BOOKED,
	PICKUP_SCHEDULED,
	PICKUP_ARRIVED,
	PICKUP_LOADED,
	PICKUP_DEPARTED,
	IN_TRANSIT,
	CUSTOMS_CLEARANCE,
	CUSTOMS_RELEASED,
	ARRIVED_AT_HUB,
	DEPARTED_FROM_HUB,
	OUT_FOR_DELIVERY,
	DELIVERY_ARRIVED,
	DELIVERY_UNLOADED,
	DELIVERED,
	PARTIALLY_DELIVERED,
	EXCEPTION,
	DELAYED,
	REROUTED,
	CANCELLED,
	CLOSED
}