package com.nexus.dms.entities;

public enum DocumentType {
    PROFILE_IMAGE,
    ID_PROOF,
    ADDRESS_PROOF,
    CONTRACT,
    INVOICE,
    REPORT,
    TRANSIT_LISENSE,
    EXPORT_PERMIT,
    PASSPORT,
    LETTER_OF_INTENT,
    JOINING_LETTER,
    SALARY_SLIP,
    RESIGNATION_LETTER,
    TERMINATION_LETTER,
    EXPERIENCE_LETTER,
    COMPENSATION_CARD,
    OTHER_HR_DOCUMENTS,
    OTHER
}
