spring.application.name=NexusBuddy
spring.profiles.active=local
#spring.datasource.url=jdbc:postgresql://db.xrcyhvcogjpbjtaiihst.supabase.co:5432/postgres?user=${supabase_uid}&password=${supabase_password}
#session-pooler connection string
#spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.xrcyhvcogjpbjtaiihst&password=${supabase_password}
#transaction-pooler connection string
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.xrcyhvcogjpbjtaiihst&password=${supabase_password}&sslmode=require&prepareThreshold=0
spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.datasource.username=${supabase_uid}
spring.datasource.password=${supabase_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Hibernate-specific settings
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.devtools.restart.enabled=false
server.port=8087

# Spring AI Google GenAI Configuration

spring.ai.google.genai.chat.model=gemini-3.1-flash-lite
spring.ai.google.genai.chat.temperature=0.7
spring.ai.google.genai.chat.options.max-tokens=2048
