spring.application.name=pms
spring.profiles.active=local

# Database Configuration (Update with your actual database details)
spring.datasource.url=jdbc:postgresql://db.xrcyhvcogjpbjtaiihst.supabase.co:5432/postgres?user=${supabase_uid}&password=${supabase_password}
spring.datasource.username=${supabase_uid}
spring.datasource.password=${supabase_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Hibernate-specific settings
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
# Flyway configuration
spring.flyway.enabled=true
spring.flyway.baselineOnMigrate=true
spring.flyway.validateOnMigrate=true
spring.devtools.restart.enabled=false

server.port=8083
dms.endpoint.url=http://localhost:8084/dms
iam.endpoint.url=http://localhost:8080/iam
hr.endpoint.url=http://localhost:8085/hr

dms.upload.org.documents=${dms.endpoint.url}/upload/org

fetch.user.org.details.url=${iam.endpoint.url}/organizations/user-org/details
verify.token.url=${iam.endpoint.url}/auth/verify
generate.token.url=${iam.endpoint.url}/auth/login
decrypt.token.url=${iam.endpoint.url}/auth/decrypt
get.user.details.url=${iam.endpoint.url}/get-user

# Generic user credentials for service-to-service communication
generic.user.id=generic_service_user
generic.password=service_password_placeholder